id: I305ADA91
ocr_import_info:
  timestamp: '2023-09-27T04:30:59.562478+00:00'
  batch_id: batch-2756
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-27 05:10:41.040285+00:00
last_modified: 2023-09-27 05:10:41.040292+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN5402
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN5402
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བྱང་ཆུབ་སེམས་དཔའི་སྤྱོད་པ་ལ་འཇུག་པའི་ཚིག་འགྲེལ་འཇམ་དབྱངས་བླ་མའི་ཞལ་ལུང་བདུད་རྩིའི་ཐིགས་པ།
  languages:
  - bo
  author: མཁན་པོ་ཀུན་དཔལ།
statistics:
  ocr_word_mean_confidence_index: 0.9959322293808947
  ocr_word_median_confidence_index: 1.0
bases:
  I3CN5404:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN5404
      total_pages: 398
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN5404.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9959322293808947
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
